name: publish to nuget

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Sign
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          folder: 'files'
          recursive: true
            
      - name: Publish LittleLogBook.Data.SqlConnectivity
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: LittleLogBook.Data.SqlConnectivity.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
